# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
defaults: &defaults
  docker:
    # specify the version here
    - image: circleci/elixir:1.4
  working_directory: ~/repo
    
version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create

  tests:
    <<: *defaults
    steps:
      - run: mix test

workflows:
  version: 2
  test:
    jobs:
      - setup
      - tests:
          requires:
            - setup