defaults: &defaults
  docker:
    # specify the version here
    - image: circleci/elixir:1.4
      environment:
        MIX_ENV: test
    - image: postgres:10-alpine-postgis
      environment:
        POSTGRES_USER: root
        POSTGRES_HOST: localhost
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Hex
          command: mix local.hex --force
      - run:
          name: Install Rebar
          command: mix local.rebar --force
      - run:
          name: Install mix dependencies
          command: mix deps.get
      - run:
          name: Create database
          command: mix ecto.create
      - run:
          name: Install node dependencies
          command: yarn install
      - run:
          name: Install example app 1 node dependencies
          working_directory: examples/example-phx-1_2
          command: yarn install
      - run:
          name: Install example app 1 node dependencies
          working_directory: examples/example-phx-1_3
          command: yarn install
      - run:
          name: Run tests
          command: ./bin/ci
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths:
            - deps
      - save_cache:
          key: v1-mix-cache
          paths:
            - deps
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build
      - save_cache:
          key: v1-build-cache
          paths:
            - _build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - assets/node_modules
      - save_cache:
          key: v1-dependencies-
          paths:
            - assets/node_modules
